Algoritmo "Contador"
/
Var
   numero, pulo, contador : inteiro


Inicio
   escreval (" ====== informe até que numero deseja contar : ====== ")
   leia (numero)
   escreval (" ====== de quanto em quanto você deseja contar ? =====")
   leia (pulo)
   contador <- 0
   enquanto (contador <= numero ) faca
      escreval (contador)
      contador <- contador +pulo
   fimenquanto
   escreval (" ==============  Terminei de contar :D ============== ")




Fimalgoritmo